[WIP] Add last action tracking.
Metta-AI/metta pull request #14
Opened 2024-12-17 22:27 UTC by treeform

2024-12-19 12:27 UTC, daveey requested changes

2024-12-19 12:27 UTC, daveey commented on devops/vast/do.py
>  #!/usr/bin/env python3
i know this is a draft. but lets try to make unrelated changes in a separate PR

2024-12-29 02:08 UTC, treeform commented on agent/simple_encoder.py
> +                10, # 'last_action'
Yes I know. The encoder has no access to env or to the right config level. How should I thread this information here?

2024-12-29 02:09 UTC, treeform commented on devops/vast/do.py
>  #!/usr/bin/env python3
This was done in another PR. When I submit this PR for real, I will merge master and it would remove this diff.

2025-01-03 17:28 UTC, treeform commented on agent/simple_encoder.py
> +                10, # 'last_action'
I figured this out.

2025-01-07 21:45 UTC, closed without merging