Daphne
Metta-AI/metta pull request #15
Opened 2024-12-18 17:33 UTC by daphnedemekas

2024-12-19 12:23 UTC, daveey requested changes

2025-01-02 23:20 UTC, daphnedemekas commented
Note:

I feel like we probably do not want to pull in my changes to the launch.json? I can revert that on this branch to the version on main.
Also I added some comments to rl/evaluator but happy to remove those if not helpful
and there's some change to the wandb file, I'm not sure why that is

2025-01-07 20:05 UTC, daveey requested changes

2025-01-07 20:05 UTC, daveey commented on agent/policy_store.py
> +        if ptype == "rand":
selector_type

2025-01-07 20:05 UTC, daveey commented on agent/policy_store.py
> +            return []
this return is not needed

2025-01-07 20:05 UTC, daveey commented on configs/env/mettagrid/mettagrid.yaml
> +    file: false
let's call it path or uri, and default to null rather than false

2025-01-07 20:05 UTC, daveey commented on devops/wandb/wandb_ttl.py
> -import argparse
why did you delete this?

2025-01-07 20:05 UTC, daveey commented on rl/pufferlib/evaluator.py
> +        self._policy_pr = policy_record #the one that plays all the matches
for comments that are longer than a word or two, put on the line above.
also put a space after #

2025-01-07 20:05 UTC, daveey commented on rl/pufferlib/evaluator.py
> +        #each index is an agent, and we reshape it into a matrix of num_envs x agents_per_env
space after #

2025-01-07 20:05 UTC, daveey commented on rl/pufferlib/evaluator.py
> +            #here, infos is actually empty
infos is not always empty. at the end of the episode they have stuff

2025-01-07 20:18 UTC, daphnedemekas commented on configs/env/mettagrid/mettagrid.yaml
> +    file: false
Ok. will change that on the mettagrid change too, would be good to merge this one first so that we can have the test pass on that one

2025-01-07 20:22 UTC, daphnedemekas commented on devops/wandb/wandb_ttl.py
> -import argparse
Lol i really don't know where these wandb changes are coming from, I don't have this file locally

2025-01-07 20:25 UTC, daveey requested changes

2025-01-07 20:25 UTC, daveey commented on configs/env/mettagrid/triangle.yaml
> +    file: configs/env/mettagrid/maps/triangle.map
i think this should be uri:

2025-01-07 20:25 UTC, daveey commented on rl/pufferlib/evaluator.py
> +                my_obs = obs[self._policy_idxs]  #observavtions that correspond to policy agent
fix comment

2025-01-07 20:27 UTC, daveey commented on devops/wandb/wandb_ttl.py
> -import argparse
that's probably the issue. the main branch does.

you can do "git checkout HEAD -- devops/wandb/wandb_ttl.py" which should restore it.

2025-01-07 20:27 UTC, daphnedemekas commented on configs/env/mettagrid/triangle.yaml
> +    file: configs/env/mettagrid/maps/triangle.map
yes! thanks for spotting

2025-01-07 20:30 UTC, closed without merging